version: '3.8'
services:
  app:
    build: .
    container_name: vendas-jaragua
    ports:
      - "8787:8787"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.162:8449/dbsolturi
      - SPRING_DATASOURCE_USERNAME=solturi
      - SPRING_DATASOURCE_PASSWORD=NuM0ea42Vj5mGPuqyv2N
    restart: always
